[package]
name = "nomos_poe_prover"
version = "0.1.0"
edition = "2021"

[dependencies]
cl = { path = "../../../cl/cl" }
equivalence_proof_statements = { path = "../../proof_statements" }
nomos_poe_risc0_proofs = { path = "../risc0_proofs" }
risc0-zkvm = { version = "1.0", features = ["prove"] }
risc0-groth16 = { version = "1.0" }
tracing = "0.1"
rand = "0.8.5"
rand_core = "0.6.0"
thiserror = "1.0.62"
anyhow = "1"
ark-bls12-381 = "0.4.0"
ark-ff = "0.4.0"
kzgrs = { path = "../../../nomos-da/kzgrs"}
once_cell = "1.19.0"
ark-poly-commit = "0.4.0"
ark-poly = "0.4.0"
ark-serialize = "0.4.0"
sha2 = "0.10"
ark-ec = "0.4.0"

[features]
metal = ["risc0-zkvm/metal"]