[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[[example]]
name = "graphql"
path = "examples/graphql.rs"
required-features = ["gql"]

[dependencies]
axum = { version = "0.6", optional = true }
async-graphql = { version = "5", optional = true, features = ["tracing"] }
async-trait = "0.1"
bytes = "1.3"
clap = { version = "4", features = ["derive", "env"], optional = true }
futures = "0.3"
nomos-http = { path = "../http", optional = true }
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", branch = "remove-async-trait", features = [
  "derive",
] }

once_cell = "1.16"
parking_lot = "0.12"
prometheus = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["sync", "macros", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
tower-http = { version = "0.3", features = ["cors", "trace"], optional = true }
thiserror = "1"

[features]
default = []
gql = ["clap", "axum", "async-graphql", "tower-http", "nomos-http/gql"]
