[package]
name = "proof_of_groth"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0", default-features = false, features = ['std'] }
serde = { version = "1.0", features = ["derive"] }
cl = { path = "../../../../cl/cl" }
groth_proof_statements = { path = "../../../proof_statements" }
ark-groth16 = "0.4.0"
ark-bls12-381 = "0.4.0"
ark-ff = "0.4.0"