[package]
name = "equivalence_proof_statements"
version = "0.1.0"
edition = "2021"

[dependencies]
cl = { path = "../../cl/cl" }
serde = { version = "1.0", features = ["derive"] }
crypto-bigint = { version = "0.5.5", features = ["serde"] }
sha2 = "0.10"
ark-bls12-381 = "0.4.0"
ark-poly = "0.4.0"
ark-ff = "0.4.0"
ark-serialize = "0.4.0"