[package]
name = "equivalence_proof_statements"
version = "0.1.0"
edition = "2021"

[dependencies]
cl = { path = "../../cl/cl" }
serde = { version = "1.0", features = ["derive"] }
crypto-bigint = { version = "0.5.5", features = ["serde"] }

[patch.crates-io]
# add RISC Zero accelerator support for all downstream usages of the following crates.
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }