[package]
name = "nomos-system-sig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

async-ctrlc = "1.2"
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", branch = "remove-async-trait", features = [
  "derive",
] }
tokio = "1.33.0"
log = "0.4.20"
futures = "0.3.28"
