[package]
name = "nomos_groth_prover"
version = "0.1.0"
edition = "2021"

[dependencies]
nomos_groth_risc0_proofs = { path = "../risc0_proofs" }
risc0-zkvm = { version = "1.0", features = ["prove"] }
risc0-groth16 = { version = "1.0" }
tracing = "0.1"
rand = "0.8.5"
rand_core = "0.6.0"
thiserror = "1.0.62"
anyhow = "1"
ark-bn254 = "0.4.0"
ark-ff = "0.4.0"
kzgrs = { path = "../../../nomos-da/kzgrs"}
once_cell = "1.19.0"
num-bigint = "0.4.6"
ark-groth16 = "0.4.0"
ark-serialize = "0.4.0"