on:
  pull_request:
  push:
    branches:
      - master

name: Codecov

jobs:
  test:
    name: Test
    env:
      RUSTFLAGS: -C instrument-coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Protobuf
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust Components
        run: |
          rustup set profile minimal
          rustup component add llvm-tools-preview --toolchain stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install risc0
        run: cargo binstall -y cargo-risczero && cargo risczero install

      - name: Install grcov
        run: cargo binstall -y grcov

      - name: Build binaries for tests
        run: |
          cargo install --path ./nodes/nomos-node --root /tmp
          cargo install --path ./nomos-cli --root /tmp
          cargo clean

      - name: Tests and Grcov
        env:
          SLOW_TEST_ENV: true
        run: |
          mkdir -p ./target/debug/
          mv /tmp/bin/* ./target/debug/
          cargo test --no-default-features --features libp2p
          mkdir -p /tmp/cov
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o /tmp/cov/tests.lcov

      - name: On Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-artifacts
          path: tests/.tmp*

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: /tmp/cov/
          name: nomos-node-codecov

